### ISSUE TITLE
Bug - Not working as reported by other users

### ISSUE THREAD

**Issue by nachog4** [ranrib/google-maps-sorter#1]
Tested on Edge Dev v116

Invalid Jquery Dom reference, probably some users of Google Maps have a different/newer version with a different DOM structure

![image](https://github.com/ranrib/google-maps-sorter/assets/14312852/a42ad7bb-ab01-426e-8963-6a2481b90284)

if any useful, tested from spain/germany logged in account
For me it was working, until two weeks ago

**Comment by nachog4** [comment]
![image](https://github.com/ranrib/google-maps-sorter/assets/14312852/054a2517-1ad3-48d2-934a-b155f427abee)

I guess thats the element referred as "role=article" in the original code (line 15)

**Comment by ranrib** [comment]
hmm yes @nachog4. I see it was changed for me as well - I'll work on a fix.

**Comment by ranrib** [comment]
@nachog4 I'm going to publish it soon to the market again.

**Comment by nachog4** [comment]
i had it fixed like this 

![image](https://github.com/ranrib/google-maps-sorter/assets/14312852/cb24af80-bc31-45b6-ab5b-ceef0710478b)
